# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-arm64/blas-1.0-openblas.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/bzip2-1.0.8-h80987f9_6.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ca-certificates-2024.9.24-hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jpeg-9e-h80987f9_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libbrotlicommon-1.0.9-h80987f9_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libcxx-14.0.6-h848a8c0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libdeflate-1.17-h80987f9_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libffi-3.4.4-hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libsodium-1.0.18-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libwebp-base-1.3.2-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/llvm-openmp-14.0.6-hc6e5704_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ncurses-6.4-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pybind11-abi-5-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2024b-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/xz-5.4.6-h80987f9_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/yaml-0.2.5-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zlib-1.2.13-h18a0788_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/expat-2.6.3-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/lerc-3.0-hc377ac9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libbrotlidec-1.0.9-h80987f9_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libbrotlienc-1.0.9-h80987f9_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libgfortran5-11.3.0-h009349e_28.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libpng-1.6.39-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/lz4-c-1.9.4-h313beb8_1.conda
https://conda.anaconda.org/conda-forge/osx-arm64/openssl-3.3.2-h8359307_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/readline-8.2-h1a28f6b_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tk-8.6.14-h6ba3021_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zeromq-4.3.5-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/brotli-bin-1.0.9-h80987f9_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/freetype-2.12.1-h1192e45_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libgfortran-5.0.0-11_3_0_hca03da5_28.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/sqlite-3.45.3-h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/zstd-1.5.6-hfb09047_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/brotli-1.0.9-h80987f9_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libopenblas-0.3.21-h269037a_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/libtiff-4.5.1-h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-3.12.7-h99e199e_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/appnope-0.1.3-py312hca03da5_1001.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/async-lru-2.0.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/attrs-23.1.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/brotli-python-1.0.9-py312h313beb8_8.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/certifi-2024.8.30-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-3.3.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/debugpy-1.6.7-py312h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/h11-0.14.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/idna-3.7-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/joblib-1.4.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/kiwisolver-1.4.4-py312h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/lcms2-2.12-hba8e193_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/markupsafe-2.1.3-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/mistune-2.0.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nest-asyncio-1.6.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numpy-base-1.26.4-py312he047099_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/openjpeg-2.5.2-h54b8e55_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/overrides-7.4.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/packaging-24.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pandocfilters-1.5.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/platformdirs-3.10.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/prometheus_client-0.14.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/psutil-5.9.0-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pygments-2.15.1-py312hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyparsing-3.1.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pysocks-1.7.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-fastjsonschema-2.16.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-json-logger-2.0.7-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pytz-2024.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyyaml-6.0.2-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pyzmq-25.1.2-py312h313beb8_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/rfc3986-validator-0.1.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/rpds-py-0.10.6-py312hf0e4da2_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/send2trash-1.8.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/setuptools-75.1.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/sniffio-1.3.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/soupsieve-2.5-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/threadpoolctl-3.5.0-py312h989b03a_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/toolz-0.12.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tornado-6.4.1-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/traitlets-5.14.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/typing_extensions-4.11.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/unicodedata2-15.1.0-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/webencodings-0.5.1-py312hca03da5_2.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/websocket-client-1.8.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/wheel-0.44.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/anyio-4.2.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/babel-2.11.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/beautifulsoup4-4.12.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/bleach-4.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/cffi-1.17.1-py312h3eb5a62_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/comm-0.2.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/cytoolz-0.12.2-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/fonttools-4.51.0-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/httpcore-1.0.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jedi-0.19.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jinja2-3.1.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_core-5.7.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/matplotlib-inline-0.1.6-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numpy-1.26.4-py312h7f4fdc5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pillow-10.4.0-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pip-24.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/prompt-toolkit-3.0.43-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/python-dateutil-2.9.0post0-py312hca03da5_2.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/referencing-0.30.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/rfc3339-validator-0.1.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/terminado-0.17.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/tinycss2-1.2.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/typing-extensions-4.11.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/urllib3-2.2.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/argon2-cffi-bindings-21.2.0-py312h80987f9_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/bottleneck-1.3.7-py312ha86b861_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/contourpy-1.2.0-py312h48ca7d4_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/httpx-0.27.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jsonschema-specifications-2023.7.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_client-8.6.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_server_terminals-0.4.4-py312hca03da5_1.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/numexpr-2.8.7-py312h0f3ea24_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.43-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/requests-2.32.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/scipy-1.13.1-py312ha409365_0.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/argon2-cffi-21.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ipython-8.27.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jsonschema-4.23.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/matplotlib-base-3.9.2-py312h2df2da3_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/pandas-2.2.2-py312hd77ebd4_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/scikit-learn-1.5.1-py312hd77ebd4_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/ipykernel-6.29.5-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_events-0.10.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/matplotlib-3.9.2-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbformat-5.10.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbclient-0.8.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/nbconvert-7.16.4-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter_server-2.14.1-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyter-lsp-2.2.0-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyterlab_server-2.27.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/notebook-shim-0.2.3-py312hca03da5_0.conda
https://repo.anaconda.com/pkgs/main/osx-arm64/jupyterlab-4.2.5-py312hca03da5_0.conda
